name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  run:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install

      - run: npm run lint
      - run: npm run build
      - run: npm test

      - uses: codfish/semantic-release-action@v1
        with:
          repository_url: https://github.com/${{github.REPOSITORY}}.git
          branch: master
          plugins: |
            [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              [
                "@semantic-release/npm", {
                  "pkgRoot": "dist"
                }
              ],
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
