name: Build on Master PR

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    name: Build on Master PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install

      - run: npm run lint
      - run: npm run build
      - run: npm test
